name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          version: 6.24.1
      - run: yarn
      - run: yarn docs:build

      - name: Deploy Shimada666.github.io/master
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: 09473ZH/09473ZH.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: docs/.vuepress/dist
        with:
          emptyCommits: false
